### ISSUE TITLE
Add entities

### ISSUE THREAD

**Issue by hyeonjun-An** [soma-lighthouse/BE-lingo-swap#4]
## 설명

- [x] 기존의 member entity를 데이터베이스 설계대로 수정
- [x] Common에 DateBasicEntity 생성
- [x] 엔티티 생성(Category Country Device Interests Language MatchedUser Member PreferredCountry PreferredInterests UsedLanguage)

## TODO (Optional)

- [x] warning없이 잘 실행되지만, 데이터 테이블 안생기는 문제 해결해야함
